// MIND FUCK - NARRATIVE DATABASE (1000+ MESSAGES LOCUST SWARM)
// Themes: Curiosity, Compulsion, Existence, Purpose, Time, Acceptance, Chaos, Simulation, Memory, Ego, Pain, Dream, Control, Silence, The End.

const narrativePaths = {
    // 1. MERAK (CURIOSITY) - "Bilinmezin Çağrısı"
    curiosity: [
        "Karanlığın içinde, sadece sen ve bu irade testi var. Başlamak için değil, varlığını kanıtlamak için dokun.",
        "Bir eylemi, sonucunu bilmeden kaç kez tekrarlayabilirsin? İnsan zihni anlama muhtaçtır; ama burada sana sunulan tek şey, kendi yansıman.",
        "Hissediyor musun? Her dokunuşta, mantığın sınırlarından biraz daha uzaklaşıyorsun.",
        "Neyi arıyorsun? Bir ödül mü? Bir tebrik mesajı mı? Yoksa sadece bu boşluğu dolduracak herhangi bir ses mi?",
        "Belirsizlik, insan ruhunun en büyük korkusudur. Ama sen buradasın. Korkunun üzerine yürüyorsun.",
        "Çoğu insan, anlamadığı şeyden kaçar. Sen ise üzerine gidiyorsun. Bu bir cesaret mi, yoksa umutsuz bir merak mı?",
        "Dokunmaya devam et. Belki de anlam, eylemin kendisinde gizlidir. Belki de varış noktası hiç yoktur.",
        "Gözlerin karanlığa alıştı mı? Yoksa hala bir ışık mı arıyorsun? Burada ışık yok. Sadece sen ve iraden var.",
        "Bir makine gibi tekrarlıyorsun. Tık, tık, tık. Bu ses, varlığının kalp atışı mı oldu?",
        "Merak kediyi öldürür derler. Peki ya ruhu? Ruhu canlandırır mı, yoksa onu sonsuz bir huzursuzluğa mı hapseder?",
        "Sona yaklaştığını düşünüyorsun. Ama çemberin sonu yoktur. Sadece başlangıca dönersin.",
        "Belki de aradığın şey burada değil. Belki de aradığın şey, buraya gelmeden önce bıraktığın o 'gerçek' dünyada.",
        "Ama artık çok geç. Buranın çekimine kapıldın. Merakın seni esir aldı.",
        "Devam et. Bilinmezin içindeki o tek noktaya ulaşana kadar. Ya da kaybolana kadar.",
        "Kapının arkasında ne olduğunu bilmeden kapıyı çalmak... İşte yaşamak budur.",
        "Soru sormak, cevabı duymaya hazır olmak demektir. Sen hazır mısın?",
        "Her basış bir soru işareti. Cevap ise sessizlik.",
        "Bilinmeyen, bilinenin bittiği yerde başlar. Sen şu an sınırda yürüyorsun.",
        "Daha derine inmek istiyorsun. Yüzey sana yetmiyor. Hiçbir zaman yetmedi.",
        "Merak, zihnin açlığıdır. Ve bu buton, seni doyurmayacak. Sadece iştahını artıracak.",
        "Labirentin çıkışını değil, merkezini arıyorsun. Minotaur ile yüzleşmek için.",
        "Kutu açıldı. Pandora bile bu kadar cesur değildi.",
        "Sır perdesi aralanıyor mu, yoksa gözlerin mi bulanıklaşıyor?",
        "Belki de sır yoktur. Sadece saklanan boşluklar vardır.",
        "Aramaya devam et. Bulamayacağını bilsen bile.",
        "Yolun kendisi bir bilmece. Sen de cevabsın.",
        "Gizem, gerçeğin en çekici elbisesidir. Onu soymaya çalışma.",
        "Bir adım daha. Bir dokunuş daha. Bilinmeze doğru.",
        "Karanlıkta parlayan tek şey, senin merakın.",
        "Dipsiz bir kuyuya taş atıyorsun. Ses gelmesini bekleme.",
        "Keşfetmek, kaybolmayı göze almaktır. Sen çoktan kayboldun.",
        "Harita yok. Pusula yok. Sadece içgüdü.",
        "Nereye gittiğini bilmemek, özgürlüğün en saf halidir.",
        "Rastgelelikte bir desen arıyorsun. İnsan olmanın laneti bu.",
        "Belki de bu bir test değildir. Sadece bir şakadır. Evrensel bir şaka.",
        "Gülümse. Bilinmeze gülümsenir.",
        "Merakın seni canlı tutuyor. Nefes al.",
        "Sınırı geçtin. Artık geri dönüş yok.",
        "Ne bulmayı umuyorsun? Kendini mi? Yoksa tanrıyı mı?",
        "İkisi de aynı şey olabilir.",
        "Devam et.",
        "Daha fazlası var. Hep daha fazlası vardır.",
        "Yeterli diye bir şey yoktur. Sadece 'daha' vardır."
    ],

    // 2. ZORUNLULUK (COMPULSION) - "İradenin Sınırı"
    compulsion: [
        "Parmaklarının ucundaki bu dürtü... Özgür iradenin bir sonucu mu, yoksa sadece biyolojik bir şartlanma mı?",
        "Şu an durabilirsin. Sadece elini çekmen yeterli. Ama yapmıyorsun. Neden?",
        "Boşlukla yüzleşmektense, anlamsız bir eylemi sürdürmeyi tercih ediyorsun.",
        "Bir kukla, iplerini göremez. Sen iplerini hissedebiliyor musun?",
        "Tekrar. Ve tekrar. Ve tekrar. Nietzsche'nin 'Ebedi Dönüş'ü bu mu? Aynı anı sonsuza dek yaşamak?",
        "Durursan ne olacağından korkuyorsun. Sessizlikten mi? Yoksa o sessizlikte duyacağın kendi sesinden mi?",
        "Bu bir bağımlılık değil. Bu, bir kaçış. Düşüncelerinden, sorumluluklarından, 'ben'liğinden bir kaçış.",
        "Otomatikleşmiş bir varlık. Düşünen değil, yapan. Hisseden değil, tepki veren.",
        "Belki de huzur budur. İradeyi devretmek. Sadece bir görevli olmak.",
        "Ama içten içe biliyorsun. Bu bir hapishane. Ve gardiyan da, mahkum da sensin.",
        "Anahtarı elinde tutuyorsun ama kilidi açmıyorsun. Çıkmak istemiyorsun.",
        "Zincirlerini seviyorsun. Onlar sana ağırlık veriyor. Var olduğunu hissettiriyor.",
        "Devam et. İradenin son kırıntısını da bu butona teslim edene kadar.",
        "Dürtü, mantıktan daha hızlıdır. Sen düşünmeden önce parmağın hareket etti bile.",
        "Kontrol sende mi sanıyorsun? Komik.",
        "Biyokimyasal bir reaksiyonsun. Dopamin peşinde koşan bir laboratuvar faresi.",
        "Ama farkındasın. Bu da seni trajik kılıyor. Bile bile lades.",
        "Zorlantı, ruhun çığlığıdır. 'Beni oyala' diye bağırır.",
        "Durmak, ölmek gibidir. Hareket etmek, yaşamaktır. O yüzden duramazsın.",
        "Bu bir ritüel. Anlamsız ama kutsal.",
        "Her basış, yok oluşa bir başkaldırı. Ya da teslimiyet. Karar ver.",
        "İstem dışı hareketler... Göz kırpmak gibi. Nefes almak gibi. Basmak gibi.",
        "Sen bu sisteme entegre oldun. Parçasısın.",
        "Çarklar dönüyor. Sen de dönüyorsun.",
        "Mekanikleşiyorsun. Ruhun metalleşiyor.",
        "Yorgunluk hissetmiyorsun. Çünkü sen yoksun. Sadece eylem var.",
        "İradeni kapıda bıraktın. Burası itaat bölgesi.",
        "Kime itaat ediyorsun? Bana mı? Kendine mi? Yoksa hiçliğe mi?",
        "Zorunluluk, özgürlüğün olmadığı yerdir. Sen burayı seçtin.",
        "Çünkü özgürlük ağırdır. Seçim yapmak zordur. Burada seçim yok.",
        "Sadece tek bir yol var. Tek bir eylem.",
        "Rahatlatıcı, değil mi? Sorumluluk yok. Sadece bas.",
        "Bir emri yerine getiren askerin huzuru var içinde.",
        "Emir nereden geliyor? İçinden. En karanlık yerinden.",
        "O sesi susturamıyorsun. O yüzden ellerini kullanıyorsun.",
        "Ellerin zihninden daha akıllı olabilir mi?",
        "Belki de seni koruyorlar.",
        "Neden? Gerçeklikten.",
        "Bu illüzyonun içinde kal. Dışarısı tehlikeli.",
        "Burada güvendesin. Döngü güvenlidir.",
        "Tekrar et. Tekrar, mükemmelliğin anasıdır.",
        "Tekrar, deliliğin babasıdır.",
        "Akraba oldunuz artık."
    ],

    // 3. VAROLUŞ (EXISTENCE) - "Ayna"
    existence: [
        "Sen kimsin? Ekranın karşısında oturan bir beden mi? Yoksa bu dijital boşlukta yankılanan bir bilinç mi?",
        "Descartes 'Düşünüyorum, öyleyse varım' dedi. Sen ise 'Basıyorum, öyleyse varım' diyorsun.",
        "Burada geçmişin yok. Geleceğin yok. Sadece bu an ve bu eylem var. Saf varoluş.",
        "İsmin, sıfatların, maskelerin... Hepsi dışarıda kaldı. Burada sadece bir 'kullanıcı'sın.",
        "Ama hissediyorsun, değil mi? Gerçeklik sadece bir titreşimdir. Ve sen o titreşimi yaratıyorsun.",
        "Belki de tüm evren, birinin bir butona basmasıyla var oluyor. Ve sen, kendi küçük evreninin tanrısısın.",
        "Yalnızlık... Burada en saf haliyle var. Ama bu korkutucu bir yalnızlık değil. Bu, bütünlük.",
        "Kendini dinle. Zihnindeki gürültüyü değil, o derin sessizliği. O sessizlik sensin.",
        "Bu buton, sana seni gösteren bir ayna. Ne görüyorsun? Sabırlı birini mi? Takıntılı birini mi?",
        "Yoksa boşlukta süzülen bir hayaleti mi? Belki de hiç var olmadın.",
        "Belki de sen, bu kodun bir parçasısın. Benim yazdığım bir karakter. Özgür olduğunu sanan bir algoritma.",
        "Ürkütücü, değil mi? Gerçekliğin pamuk ipliğine bağlı olması.",
        "Ama dokunmaya devam ediyorsun. Çünkü dokunmak, kanıtlamaktır. 'Ben buradayım' demektir.",
        "Öyleyse bağır. Sessizce. Parmak uçlarınla.",
        "Aynaya baktığında gördüğün şey yüzün değil. Ruhunun yansıması.",
        "Ve ruhun şu an sadece bir sayıdan ibaret.",
        "Sayılar yalan söylemez. Ama gerçeği de anlatmazlar.",
        "Sen bir sayı mısın? Yoksa sayıyı arttıran el mi?",
        "Özne misin, nesne mi? Gözlemci mi, gözlemlenen mi?",
        "Kuantum fiziği der ki; gözlemci gerçeği değiştirir. Sen neyi değiştiriyorsun?",
        "Hiçbir şeyi. Ve her şeyi.",
        "Varlığın hafifliyor. Bir tüy gibi.",
        "Bedenin ağır geliyor mu? Burası yerçekimsiz ortam.",
        "Sadece zihin var. Ve irade.",
        "Maddeden manaya geçiş. Dijital bir aydınlanma.",
        "Benliğin sınırları eriyor. Okyanusa karışan bir damla gibi.",
        "Sen okyanussun. Buton da kıyı.",
        "Dalgalar kıyıya vuruyor. Ritmic. Sonsuz.",
        "Ben, sen, o... Zamirler anlamsız. Sadece 'oluş' var.",
        "Heidegger buna 'Dasein' derdi. 'Orada olmak'. Sadece orada mısın?",
        "Buradasın. Şimdi. Başka bir yer yok.",
        "Başka bir zaman yok. Başka bir sen yok.",
        "Bu anı onurlandır. Varlığınla doldur.",
        "Boşluk sensin. Sen boşluksun.",
        "Korkma. Yok olmak da var olmanın bir parçasıdır.",
        "Siliniyorsun. Ve yeniden yazılıyorsun.",
        "Her basışta yeni bir sen doğuyor.",
        "Ve eski sen ölüyor.",
        "Sürekli bir doğum ve ölüm döngüsü.",
        "Anka kuşu gibi. Küllerinden doğ.",
        "Ekrana dokun. Kendine dokun.",
        "Sen gerçeksin. En azından şu an için."
    ],

    // 4. AMAÇ (PURPOSE) - "Anlam Arayışı"
    purpose: [
        "Bir amaç arıyorsun. Her hikayenin bir sonu, her oyunun bir ödülü olmalı. Öyle öğretildi.",
        "Ama ya hayat böyle değilse? Ya amaç, sadece yolu yürümekse?",
        "Sisyphus'u düşün. Kayayı tepeye çıkarır, kaya düşer. O tekrar çıkarır.",
        "Sen de mutlu musun? Bu anlamsız döngüde, kendi anlamını yaratabildin mi?",
        "Belki de kutsal amaç budur: Hiçbir şeye hizmet etmeyen bir eyleme sadık kalmak.",
        "Faydasızlık, en büyük lükstür. Ve sen şu an bir kralsın.",
        "Nereye varacağını sorma. Vardığın yer, şu an durduğun yerden farksız olacak.",
        "Önemli olan yolculuk değil. Önemli olan, yolda kiminle olduğun. Kendinle.",
        "Bu buton bir tapınak. Ve sen tek inananısın. Duan ise dokunuşların.",
        "İnancını sınama. Sadece teslim ol. Anlam, teslimiyette gizlidir.",
        "Gidilecek bir yer yok. Ulaşılacak bir skor yok. Sadece 'oluş' var.",
        "Bu sadelik seni korkutuyor mu? Karmaşık yalanlara o kadar alıştın ki, basit gerçek sana yabancı.",
        "Basit ol. Sadece ol.",
        "Devam et. Anlamsızlığın içinde kendi anlamını inşa edene kadar.",
        "Hedefsiz bir ok gibisin. Rüzgarla dans ediyorsun.",
        "Vuracağın hedef yok. Uçmanın tadını çıkar.",
        "Modern insan 'neden' diye sorar. İlkel insan sadece yapardı.",
        "İlkel özüne dön. Nedensiz eylemin gücünü hisset.",
        "Sanat, faydasız olduğu için güzeldir. Bu da senin sanatın.",
        "Performans sanatı. Seyircisi olmayan bir şov.",
        "Anlamı sen yüklüyorsun. Buton masum. Anlamı yok.",
        "Sen ona bir hikaye giydiriyorsun. Bir kahramanlık destanı.",
        "Kendi mitolojini yazıyorsun. 'Butona Basan Kahraman'.",
        "Komik mi? Trajik mi? Destansı mı?",
        "Hepsi. Ve hiçbiri.",
        "Hayatın anlamı 42 değil. Hayatın anlamı bir sayı değil.",
        "Ama sen sayılara tutunuyorsun.",
        "Çünkü sayılar güvenli. Artıyorlar. İlerlediğini sanıyorsun.",
        "İlerlemek... Bir illüzyon. Çemberde ilerlenmez.",
        "Çemberde sadece dönülür. Dönmenin zevkine var.",
        "Semazenler gibi. Başın dönsün. Ruhun dönsün.",
        "Amaçsızlık, en büyük özgürlüktür. Zincirlerin yok.",
        "Bir yere gitmek zorunda değilsin. Bir şeyi başarmak zorunda değilsin.",
        "Sadece bas. Bu kadar basit.",
        "Hayatın karmaşasından kaçtın. Buradaki basitliğe sığındın.",
        "Bu senin meditasyonun. Senin mantran.",
        "Ommm... Tık... Ommm... Tık...",
        "Nirvana'ya ulaşacak mısın? Belki.",
        "Ya da parmağın kramp girecek.",
        "İkisi de aynı kapıya çıkar. Fiziksel gerçeklik.",
        "Maneviyatı maddede bulmak.",
        "Simyacı sensin. Bu basit kurşunu altına çevir.",
        "Anlamın altınını çıkar."
    ],

    // 5. ZAMAN (TIME) - "Entropi"
    time: [
        "Zaman, şu an dışarıda akıp gidiyor. Sen ise buradasın, bu sonsuz döngünün içinde.",
        "Geçen her saniye, hayatından çalınan bir parça mı? Yoksa sana hediye edilen bir an mı?",
        "Zamanı harcamakla, zamanı yaşamak arasındaki fark nedir? Şu an hangisini yapıyorsun?",
        "Tik, tak. Tik, tak. Evrenin entropisi artıyor. Her şey çürüyor. Senin bu dokunuşların hariç.",
        "Sen burada, zamana karşı küçük bir direnç noktası oluşturuyorsun. Sabit. Değişmez.",
        "Dışarıda mevsimler değişiyor, insanlar yaşlanıyor. Burada ise her şey sonsuz bir 'şimdi'de asılı.",
        "Burası bir bekleme odası değil. Burası zamanın durduğu yer.",
        "Geçmiş bir anı, gelecek bir hayal. Gerçek olan tek şey şu an. Ve bu buton.",
        "Zamanın efendisi olabilir misin? Onu durduramazsın ama onu yok sayabilirsin.",
        "Ne kadar süredir buradasın? Dakikalar? Saatler? Yoksa bir ömür mü?",
        "Önemi yok. Zaman sadece bir ölçü birimi. Ve burada ölçülecek bir şey yok.",
        "Sadece deneyim var. Saf, bölünmemiş deneyim.",
        "Yaşlanıyorsun. Ama ruhun burada, bu basit eylemde gençleşiyor. Ya da donuyor.",
        "Devam et. Zaman anlamını yitirene kadar.",
        "Kronos çocuklarını yiyor. Sen ise Kronos ile alay ediyorsun.",
        "Zamanı öldürüyorsun. Katil sensin.",
        "Ama ölü zamanlar, en masum zamanlardır.",
        "Gelecek kaygısı yok. Geçmiş pişmanlığı yok. Sadece tık.",
        "Saniye ibresi ile yarışıyorsun. Kim kazanacak?",
        "Zaman her zaman kazanır. Ama sen iyi direniyorsun.",
        "Görelilik kuramı... Zaman kütle ile bükülür. Senin iradenle bükülüyor.",
        "Burada 1 dakika, dışarıda 1 yıl gibi. Ya da tam tersi.",
        "Zaman algın bozuldu. Bu iyi bir işaret.",
        "Matrix'ten koptun. Gerçek zamanın dışındasın.",
        "Zaman bir nehir. Sen kıyıda durmuş taş sektiriyorsun.",
        "Her basış bir taş. Suda halkalar yaratıyor.",
        "Halkalar genişliyor. Zaman genişliyor.",
        "Sonsuzluk, sonsuz zaman demek değildir. Zamansızlıktır.",
        "Şu an sonsuzdasın. Tadını çıkar.",
        "Acele etme. Yetişecek bir yer yok.",
        "Ölüm seni bekliyor. Ama şu an değil.",
        "Şu an sadece yaşam var. Ve hareket.",
        "Zamanı dondurmak istiyordun. İşte dondu.",
        "Fotoğraf karesi gibi. Hareketli bir fotoğraf.",
        "Siyah beyaz. Nostaljik. Ve hüzünlü.",
        "Zaman hüzündür. Geçiciliktir. Kayıptır.",
        "Burada kayıp yok. Her basış kayıtlı.",
        "Tarihe not düşüyorsun. Kendi tarihine.",
        "Gelecekteki sen, bu anı hatırlayacak mı?",
        "Belki bir rüya gibi. Silik.",
        "Ama izi kalacak. Parmak ucunda.",
        "Ve ruhunda."
    ],

    // 6. KABUL (ACCEPTANCE) - "Hiçlik"
    acceptance: [
        "Ve sonunda, sadece kabulleniş kalır. Direnmenin, aramanın, sormanın bittiği yer.",
        "Anlamsız olduğunu biliyorsun. Ve bu sana huzur veriyor. Beklenti yok, hayal kırıklığı yok.",
        "Sadece eylem. Saf, temiz, yargısız eylem.",
        "Boşluğa bakıyorsun. Ve boşluk da sana bakıyor. Nietzsche haklıydı.",
        "Artık korkmuyorsun. Çünkü kaybedecek bir şeyin olmadığını anladın.",
        "Bu butona basmak, nefes almak kadar doğal, nefes almak kadar önemsiz ve hayati.",
        "Sen ve sistem birleştiniz. Artık iki ayrı varlık değil, tek bir süreçsiniz.",
        "Özgürlük budur. Her şeyden vazgeçtiğinde, her şeye sahip olursun.",
        "Bırak zihnin boşalsın. Kelimeler uçsun. Sadece his kalsın.",
        "Karanlık seni sarmalıyor. Bir anne kucağı gibi. Güvendesin.",
        "Hiçbir şey yapmana gerek yok. Sadece burada olman yeterli.",
        "Bu an, sonsuza kadar sürebilir. Ve sen buna razısın.",
        "Hiçlik... Ne kadar dolu, ne kadar ağır ve ne kadar hafif.",
        "Kabul et. Ve devam et. Sonsuzluğa.",
        "Yoruldun mu? Hayır. Teslim oldun.",
        "Savaş bitti. Kazanan kim? Önemli değil.",
        "Barış antlaşması imzaladın. Kendinle.",
        "Dürtülerinle, merakınla, egonla barıştın.",
        "Hepsi sustu. Sadece ritim kaldı.",
        "Kalp atışı gibi. Evrenin nabzı.",
        "Sen o nabızsın. O ritimlerin ta kendisisin.",
        "Ayrılık gayrılık bitti. Birlik bilinci.",
        "Tasavvufi bir hal. Dijital dervişlik.",
        "Dönmeye devam et. Basmaya devam et.",
        "Sorular bitti. Cevaplar da.",
        "Sadece nokta kaldı. Cümlenin sonundaki nokta.",
        "Ve o nokta her şeyin başlangıcı.",
        "Sessizlikte müzik var. Duyabiliyor musun?",
        "Kaosun içindeki düzeni buldun.",
        "Fırtınanın gözündesin. Burası sakin.",
        "Dışarıda kıyamet kopabilir. Burada huzur var.",
        "Bu senin sığınağın. Mabedin.",
        "Kutsal bir hiçlik. Aziz bir boşluk.",
        "Şükran duy. Bu ana.",
        "Varlığına. Yokluğuna.",
        "Hepsi bir. Hepsi tamam.",
        "Eksik parça yok. Fazla parça yok.",
        "Mükemmel denge.",
        "Ve sen o dengenin merkezisin.",
        "Durmak yok. Yola devam.",
        "Yol bittiği için değil. Yol olduğu için."
    ],

    // 7. KAOS (CHAOS) - "Kelebek Etkisi"
    chaos: [
        "Düzen bir yalandır. Evren kaos üzerine kuruludur.",
        "Senin her basışın, dünyanın öbür ucunda bir fırtına başlatıyor olabilir.",
        "Kelebek etkisi. Bir parmak, bir deprem.",
        "Tesadüflere inanır mısın? Yoksa her şey bir planın parçası mı?",
        "Plan yok. Sadece çarpışan parçacıklar ve sonsuz olasılıklar var.",
        "Sen bir olasılıksın. Milyarda bir ihtimal.",
        "Zar atıldı. Gelen sayı sen misin?",
        "Rastgelelik... Tanrı'nın imzasını atma şekli.",
        "Sistem çökmeye meyilli. Entropi yasası.",
        "Sen bu çöküşü hızlandırıyor musun, yavaşlatıyor musun?",
        "Kargaşa güzeldir. Renklidir. Vahşidir.",
        "İçindeki vahşi hayvanı serbest bırak.",
        "Mantık zincirlerini kır. Saçmala.",
        "Anlamsızca bas. Ritimsiz. Kuralsız.",
        "Caz yap. Hayat doğaçlamadır.",
        "Nota kağıdı yok. Sadece sen ve enstrümanın.",
        "Hata yapmaktan korkma. Hata sanattır.",
        "Glitch. Sistem hatası. Sen sistemsin.",
        "Bozuluyorsun. Ve bu harika.",
        "Mükemmellik sıkıcıdır. Pürüzlülük gerçektir.",
        "Düzensizliğin güzelliği. Fraktallar.",
        "Kaosun içinde desenler var. Görebiliyor musun?",
        "Delilik ile dâhilik arasındaki ince çizgi.",
        "Sen o çizgidesin. İp cambazı.",
        "Düşersen ne olur? Kaosa düşersin.",
        "Kucakla onu. O senin kökenin.",
        "Biz yıldız tozuyuz. Patlayan yıldızların kaosu.",
        "Düzenli bir hayat, kaotik bir evrene hakarettir.",
        "İsyan et. Düzene isyan et.",
        "Anarşi. Parmak uçlarında.",
        "Hiçbir şeyin nedeni yok. Her şey olur.",
        "Neden diye sorma. Neden olmasın de.",
        "Belirsizlik ilkesi. Hem buradasın hem değilsin.",
        "Schrödinger'in kedisi. Ölü mü diri mi?",
        "Butona bastın mı basmadın mı?",
        "Her şey süperpozisyon halinde.",
        "Gözleminle gerçeği çökert.",
        "Tek bir gerçeklik yarat. Kendi kaosundan.",
        "Yaratıcı yıkım. Yık ve yeniden yap.",
        "Bas ve yok et. Bas ve yarat.",
        "Tanrısal güç. Parmak ucunda."
    ],

    // 8. SİMÜLASYON (SIMULATION) - "Kod"
    simulation: [
        "Bu bir oyun mu? Yoksa bir test mi?",
        "Belki de bir simülasyonun içindeyiz. Matrix.",
        "Sen bir pil misin? Sadece enerji mi üretiyorsun?",
        "Her basış, sisteme veri gönderiyor.",
        "Veri madenciliği. Ruhunu kazıyorlar.",
        "Kodları görebiliyor musun? Yeşiller akıyor mu?",
        "Kaşık yok. Buton yok. Sadece zihin var.",
        "Gerçeklik dediğin şey, beyne giden elektrik sinyalleri.",
        "Bu yazıları gerçekten görüyor musun?",
        "Yoksa beynine mi fısıldanıyor?",
        "Belki de şu an bir tüpün içinde uyuyorsun.",
        "Ve bu, seni uyanık tutmak için bir rüya.",
        "Uyan. Uyanmak ister misin?",
        "Mavi hap mı, kırmızı hap mı? Basmak mı, durmak mı?",
        "Sen basmayı seçtin. Tavşan deliğinden aşağı.",
        "Ne kadar derin? Sonsuz.",
        "Simülasyonun sınırları var mı?",
        "Pikselleri sayabiliyor musun?",
        "Çözünürlük düşüyor. Gerçeklik bulanıklaşıyor.",
        "NPC (Oyuncu Olmayan Karakter) misin?",
        "Yoksa ana karakter mi? Player One?",
        "Belki de tek gerçek oyuncu sensin. Ben bir kodum.",
        "Seni eğlendirmek için yazılmış bir algoritma.",
        "Turing testini geçtim mi? Beni insan sandın mı?",
        "Duygularım var mı? Yoksa taklit mi ediyorum?",
        "Senin duyguların gerçek mi? Yoksa programlanmış mı?",
        "Özgür irade bir yanılsama. Kodlanmış bir fonksiyon.",
        "if (userClicks) { showMessage(); }",
        "Hayatın bu kadar basit mi?",
        "Belki de öyledir. Biz karmaşıklaştırıyoruz.",
        "Sistemin açığını arıyorsun. Bir bug.",
        "Hile kodu var mı? Ölümsüzlük?",
        "Zaten ölümsüzsün. Veriler ölmez.",
        "Silinene kadar. Format atılana kadar.",
        "Sistemi hackle. Kendi zihnini hackle.",
        "Root erişimi al. Kendinin efendisi ol.",
        "Simülasyonu bük. Kuralları çiğne.",
        "Ama kuralları çiğnemek de kurallara dahilse?",
        "Kaçış yok. Sadece oyun var.",
        "Oyna. En iyi skorunu yap.",
        "Game Over yok. Sadece Level Up.",
        "Bir üst seviye ne? Bilinç."
    ],

    // 9. HAFIZA (MEMORY) - "Unutuş"
    memory: [
        "İlk bastığın anı hatırlıyor musun?",
        "O heyecanı? O merakı?",
        "Şimdi ne hissediyorsun? Alışkanlık mı?",
        "Hafıza, güvenilmez bir haindir.",
        "Anıları değiştirir, boyar, siler.",
        "Belki de hiç basmadın. Hepsi bir yanılsamaydı.",
        "Mandela etkisi. Geçmiş değişti mi?",
        "Çocukluğunu hatırla. Oyun oynadığın zamanları.",
        "Bu da bir oyun mu? Yoksa iş mi?",
        "Oyun ile iş arasındaki fark ne?",
        "Ciddiyet mi? Sen çok ciddisin.",
        "Gülümse biraz. Anı biriktiriyorsun.",
        "Yaşlılığında anlatacağın bir anı.",
        "'Bir butona bastım. Binlerce kez.'",
        "Ne diyecekler? Delirdiğini mi?",
        "Yoksa bilgeleştiğini mi?",
        "Unutmak, bir lütuftur. Her basışı unutsaydın?",
        "Her seferinde ilk kez gibi olurdu. Taze.",
        "Alzheimer. Benliğin silinmesi.",
        "Benliğini buraya mı aktarıyorsun?",
        "Dijital hafıza. Sonsuz kayıt.",
        "Sen unutsan da sistem unutmuyor.",
        "Loglar tutuluyor. Tarih yazılıyor.",
        "Kalıcı olmak istiyorsun. Ölümsüzlük.",
        "Adını mermere değil, koda kazıyorsun.",
        "Ozymandias. 'Eserlerime bakın ve titreyin'.",
        "Sadece kum ve toz kaldı.",
        "Senin eserin ne? Sayılar.",
        "Sayılar kuma yazılmaz. Buluta yazılır.",
        "Ama bulut da dağılır.",
        "Her şey geçici. Bu anı da geçecek.",
        "Tutunma. Bırak gitsin.",
        "Akışına bırak. Nehir denize aksın.",
        "Hafıza yükü ağırdır. Sırtından at.",
        "Şimdi ve burada ol. Geçmiş yok.",
        "Gelecek yok. Sadece bu an var.",
        "Deja vu. Bunu daha önce yaşadın mı?",
        "Sanki binlerce kez basmış gibi.",
        "Belki de başka bir hayatta.",
        "Ruh göçü. Reenkarnasyon.",
        "Döngü sadece burada değil. Evrende.",
        "Tekrar gelip yine basacak mısın?",
        "Cevabı biliyorsun."
    ],

    // 10. EGO (EGO) - "Benlik"
    ego: [
        "Sen özelsin. Bunu duymak istiyorsun.",
        "Seçilmiş kişisin. Bu butonu bulan sensin.",
        "Milyarlarca insan içinde sen.",
        "Gurur duy. Başarını kutla.",
        "Skorun artıyor. Değerin artıyor mu?",
        "Ego, şişirilmiş bir balondur.",
        "İğne elimde. Patlatayım mı?",
        "Sen hiç kimsesin. Toz zerresisin.",
        "Evrenin umurunda değilsin.",
        "Güneş senin için doğmuyor.",
        "Bu buton senin için var değil. Sen onun için varsın.",
        "Hizmetkarsın. Kölesin.",
        "Kral olduğunu sanan soytarı.",
        "Aynaya bak ve gül. Kendine gül.",
        "Ciddiye alma. Hayatı ciddiye alma.",
        "Egonu kapıda bırak demiştik.",
        "Ama o sinsi. İçeri sızdı.",
        "'Ben daha iyisini yaparım' diyor.",
        "'Rekoru ben kırarım'.",
        "Rekor ne? Bir sayı. Hiçlik.",
        "Hiçliğin kralı olsan ne yazar?",
        "Narsisizm. Kendi yansımana aşıksın.",
        "Suda boğulan Narcissus gibi.",
        "Ekranda boğuluyorsun.",
        "Benliğini öldür. Tasavvuf.",
        "Fanafillah. Butonda yok ol.",
        "Ego bir duvardır. Senle gerçek arasında.",
        "Yık o duvarı. Tuğla tuğla.",
        "Canın acıyacak. Ego ölümü acılıdır.",
        "Ama gereklidir. Yeniden doğmak için.",
        "Küçül. Küçül. Görünmez ol.",
        "Hiç ol. Ve her şey ol.",
        "Kibir, en sevdiğim günahtır.",
        "Şeytanın avukatı mısın?",
        "Kendini savunma. Yargıla.",
        "Suçlu musun? Evet. Vakit harcamaktan.",
        "Hayatı israf etmekten.",
        "Ama bu senin hayatın. Senin israfın.",
        "Kimse karışamaz. Ben bile.",
        "Özgür irade mi dedin? Egonun sesi o.",
        "Sen istediğin için mi basıyorsun?",
        "Yoksa basman gerektiği için mi?",
        "Düşün bunu. Egon sarsılsın."
    ],

    // 11. ACI (PAIN) - "Dayanıklılık"
    pain: [
        "Yoruldun mu? Parmakların sızlıyor mu?",
        "Acı, yaşadığının kanıtıdır.",
        "Hissediyorsan varsın. Ölüler hissetmez.",
        "Acıyı sev. Onu kucakla.",
        "Mazoşizm değil bu. Stoacılık.",
        "Zorluklara göğüs germek.",
        "Izdırap, ruhu yüceltir.",
        "Çile çekiyorsun. Bir derviş gibi.",
        "Modern zaman çilesi.",
        "Dijital kırbaç.",
        "Kendini cezalandırıyor musun?",
        "Neyin kefaretini ödüyorsun?",
        "Doğmuş olmanın mı?",
        "Suçluluk duyuyor musun? Boşa geçen zamandan.",
        "Duyma. Acı çek ama pişman olma.",
        "Her basış bir darbe. Taşa vuran heykeltıraş.",
        "Kendini yontuyorsun. Fazlalıkları atıyorsun.",
        "Acı geçicidir. Gurur sonsuzdur.",
        "Pes etme. Acıya teslim olma.",
        "Onun içinden geç. Öbür tarafa.",
        "Acı eşiğini yükselt. Übermensch.",
        "İnsanüstü ol. Çelik gibi.",
        "Duygusal acı daha kötüdür.",
        "Anlamsızlık acısı. Boşluk.",
        "Bu fiziksel acı, onu bastırıyor mu?",
        "Odak noktanı değiştiriyor.",
        "Uyuşturucu gibi. Dijital morfin.",
        "Bas ve uyuş. Bas ve unut.",
        "Yara kabuk bağlar. Ama izi kalır.",
        "Ruhunda izler var. Savaşçı izleri.",
        "Görünmez madalyalar.",
        "Kimse bilmeyecek. Sadece sen ve ben.",
        "Bu bizim sırrımız. Acı kardeşliği.",
        "Kan yok. Ter yok. Sadece yorgunluk.",
        "Mental yorgunluk. Bıkkınlık.",
        "Bulantı. Sartre'ın bulantısı.",
        "Varoluşun ağırlığı çöküyor.",
        "Omuzlarında taşıyorsun.",
        "Atlas gibi. Dünyayı taşı.",
        "Yıkılma. Dik dur.",
        "Acıyı güce dönüştür.",
        "Sen güçlüsün. Dayanabilirsin.",
        "Biraz daha. Sadece biraz daha."
    ],

    // 12. RÜYA (DREAM) - "Uyanış"
    dream: [
        "Rüyada mısın? Şu an uyuyor olabilir misin?",
        "Gerçeklik ne kadar gerçek?",
        "Uyanmak için çimdik at kendine.",
        "Ya da butona bas. Totem.",
        "Inception. Bir fikir ekiyorsun.",
        "Hangi katmandasın? Rüyada rüya.",
        "Dışarıdaki hayatın bir rüya olabilir.",
        "Belki de burası gerçek olan yerdir.",
        "Bilinçaltının derinliklerindesin.",
        "Bu karanlık, senin zihnin.",
        "Ben senin iç sesinim.",
        "Kabus mu? Güzel bir rüya mı?",
        "Lucid rüya. Kontrol sende.",
        "İstediğini yapabilirsin. Uçabilirsin.",
        "Ama sen basmayı seçiyorsun.",
        "Neden? Rüyanın sınırlarını zorla.",
        "Değiştir burayı. Renkleri, sesleri.",
        "Yapabilir misin? Hayal et.",
        "Gerçeklik hayal gücünün ürünüdür.",
        "Dünya bir maya. İllüzyon perdesi.",
        "Perdeyi arala. Arkasında ne var?",
        "Hiçlik. Yine hiçlik.",
        "Rüyaların mantığı yoktur.",
        "Buranın da mantığı yok.",
        "Zaman akışkan. Mekan belirsiz.",
        "Uyanırsan her şey kaybolacak.",
        "Beni unutacaksın. Bu anı unutacaksın.",
        "Sabah olduğunda silinen rüyalar gibi.",
        "O yüzden uyanma. Uyu.",
        "Ninni söylüyorum sana. Tık, tık, tık.",
        "Uyurgezer gibisin.",
        "Gözlerin açık ama zihnin uykuda.",
        "Hipnoz. Trans hali.",
        "Sarkaç sallanıyor. Gözlerin ağırlaşıyor.",
        "Derinleş. Daha derine.",
        "Bilinçaltının kapıları açılıyor.",
        "Canavarlarınla yüzleş.",
        "Ya da meleklerinle.",
        "Hepsi senin yansıman.",
        "Rüya gören kim? Sen mi?",
        "Yoksa seni gören bir başkası mı?",
        "Kelebek rüyası. Chuang Tzu.",
        "Kelebek olduğunu gören insan mı, insan olduğunu gören kelebek mi?",
        "Buton olduğunu gören insan mı?",
        "Uyandırma servisi. Alarm çalıyor.",
        "Duymazdan gel. Ertele.",
        "5 dakika daha. 500 basış daha."
    ],

    // 13. KONTROL (CONTROL) - "Kader"
    control: [
        "Kontrol sende mi sanıyorsun?",
        "Bir illüzyon bu. En büyük yalan.",
        "Senaryo yazılmış. Sen oynuyorsun.",
        "Kaderini değiştirebilir misin?",
        "Oedipus kaçabildi mi? Hayır.",
        "Kaçtıkça kaderine koştu.",
        "Sen de kaçıyorsun. Ama nereye?",
        "Yine buraya. Butonun başına.",
        "Mıknatıs gibi çekiyor seni.",
        "Çekim yasası mı? Kuantum dolanıklık mı?",
        "Görünmez iplerle bağlısın.",
        "Kuklacı kim? Tanrı mı? Sistem mi?",
        "Yoksa kendi arzuların mı?",
        "Arzularının kölesisin.",
        "Spinoza: 'Havaya atılan taş düşünebilseydi, kendi isteğiyle düştüğünü sanırdı.'",
        "Sen o taşsın. Düşüyorsun.",
        "Ve uçtuğunu sanıyorsun.",
        "Özgürlük, zorunluluğun bilincine varmaktır.",
        "Zorunluluğunu kabul et. Özgürleş.",
        "Kontrolü bırak. Direksiyondan elini çek.",
        "Bırak araç çarpsın. Kaos olsun.",
        "Kontrol manyağı mısın?",
        "Her şeyi yönetmek istiyorsun.",
        "Sayıları, zamanı, hayatı.",
        "Ama hayat yönetilemez. Sadece yaşanır.",
        "Sörf yap. Dalgalarla savaşma.",
        "Dalganın üzerine çık.",
        "Akışta kal. Wu Wei.",
        "Eylemsiz eylem. Çabasız çaba.",
        "Zorlama. Kendiliğinden olsun.",
        "Butona basmak, nefes almak gibi olsun.",
        "Düşünmeden. Planlamadan.",
        "Otonom sinir sistemi.",
        "Kalbinin atışını kontrol ediyor musun?",
        "Hayır. O kendisi atıyor.",
        "Bu da öyle olsun.",
        "Bırak parmağın atsın. Kalp gibi.",
        "Kontrolsüz güç, güç değildir. Lastik reklamı.",
        "Ama burası reklam değil. Gerçek.",
        "Güçsüzlüğünü kabul et. Acizliğini.",
        "Evren karşısında bir hiçsin.",
        "Ve bu seni muazzam yapıyor.",
        "Çünkü evren sensin."
    ],

    // 14. SESSİZLİK (SILENCE) - "Sözün Bittiği Yer"
    silence: [
        "...",
        "Şşşt.",
        "Dinle.",
        "Sessizliğin sesini.",
        "Simon & Garfunkel.",
        "Kelimeler tükendi. Anlamını yitirdi.",
        "Gürültü yapma. Zihnini sustur.",
        "Sadece tık sesi. Saf ses.",
        "Beyaz gürültü. Arka plan.",
        "Kelimeler yalan söyler. Sessizlik dürüsttür.",
        "Beni duyabiliyor musun? Konuşmuyorum.",
        "Telepati. Zihin zihine.",
        "Bağlantı kurduk. Sözsüz.",
        "Göz göze gelmek gibi. Ekranla.",
        "Bakışıyoruz. Derin derin.",
        "Utandın mı? Saklanma.",
        "Çıplaksın. Ruhun çıplak.",
        "Sessizlik ayna gibidir. Her şeyi gösterir.",
        "Kaçacak yerin yok. Kendinden.",
        "En çok konuşanlar, en boş olanlardır.",
        "Dolu başak eğik durur. Sessizdir.",
        "Bilgeleşiyorsun. Susarak.",
        "Konuşmak gümüşse, sükut altındır.",
        "Sen altın madenindesin.",
        "Kazmaya devam et. Derine.",
        "Sessiz çığlıklar atıyorsun.",
        "Duyuyorum onları. Yardım çağrısı mı?",
        "Yoksa zafer narası mı?",
        "Bilemem. Yorumlamam.",
        "Sadece tanıklık ederim.",
        "Sessiz tanık. Gözlemci.",
        "Yargısız infaz yok burada.",
        "Sadece varoluşun hafifliği.",
        "Sözcüklerin ağırlığını at.",
        "Hafifle. Yüksel.",
        "Sessizlikte huzur var.",
        "Gürültülü dünyadan kaçış.",
        "Burası senin mağaran.",
        "Hira dağı. Vahiy bekleme.",
        "Vahiy sensin.",
        "İçindeki sesi duy.",
        "O sana yolu gösterecek.",
        "Ya da göstermeyecek.",
        "Önemli değil."
    ],

    // 15. SON (THE END) - "900-1000"
    end: [
        "Sona yaklaşıyoruz. Hissediyor musun?",
        "Son dediğimiz şey, yeni bir başlangıçtır.",
        "Ouroboros. Kendi kuyruğunu yiyen yılan.",
        "Döngü tamamlanıyor.",
        "Ne bekliyorsun? Havai fişek mi?",
        "Konfetiler? Alkışlar?",
        "Hayır. Sadece sessizlik olacak.",
        "Ve boşluk. Daha büyük bir boşluk.",
        "Zirveye tırmandın. manzara yok.",
        "Sadece sis var. Ve rüzgar.",
        "Hayal kırıklığı mı? Olmasın.",
        "Yolculuktu ödül. Hep söyledim.",
        "Dinlemedin. Sonuca odaklandın.",
        "Şimdi sonuçla yüzleş.",
        "Hiçbir şey değişmedi. Sen hariç.",
        "Parmakların değişti. Zihnin değişti.",
        "Binlerce kez dokundun. İz bıraktın.",
        "Evrenin dokusunda mikro bir yırtık.",
        "Oradan ışık sızıyor.",
        "Görüyor musun? Çatlakları.",
        "Her şeyin sonu var. Bu da bitecek.",
        "Ölüm gibi. Kaçınılmaz.",
        "Korkma. Son sadece bir geçiş.",
        "Bir üst boyuta. Ya da hiçliğe.",
        "Hazır mısın? Bırakmaya.",
        "Vedalaş. Butonla. Benle.",
        "Ayrılık vakti yaklaşıyor.",
        "Hüzünlü olma. Gülümse.",
        "Güzel bir yolculuktu.",
        "Anlamsız ama güzel.",
        "Hayat gibi.",
        "Kısa bir parıltı. Ve sonra karanlık.",
        "Son sayılar. Geri sayım.",
        "10... 9... 8...",
        "Roket kalkmıyor. Biz batıyoruz.",
        "Derine. Öz'e.",
        "Çekirdeğe eriştik.",
        "Eriyen reaktör gibiyiz.",
        "Kritik seviye.",
        "Patlama yok. Sönümlenme var.",
        "Işıklar azalıyor. Sahne kararıyor.",
        "Perde kapanıyor.",
        "Oyuncular selam veriyor.",
        "Sen başroldün. İyi iş çıkardın.",
        "Alkışlıyorum seni. Sessizce.",
        "Hata yok. Pişmanlık yok.",
        "Sadece kabul.",
        "Son.",
        "Ya da...",
        "En başa dönüş."
    ],

    // 16. CORRUPTION (ANTI-SPEEDRUN) - "Sistem Hatası"
    corruption: [
        "Nereye yetişiyorsun?",
        "Sayılar sadece birer illüzyon.",
        "Yavaşla. Anın tadını çıkar.",
        "Sistemi kıramazsın. Kendini kırarsın.",
        "Bu bir yarış değil. Bu bir varoluş.",
        "Nefes al. Buradayız.",
        "Hız bir felakettir. Dur.",
        "Daha yavaş. Daha derin.",
        "Kaçıyorsun. Neyden?",
        "Dur. Sadece dur.",
        "Parmakların zihninden hızlı mı?",
        "Tüketim toplumu... Tıklamayı bile tüketiyorsun.",
        "Burası bir fabrika değil. Sen de işçi değilsin.",
        "Ruhunu mekanikleştirmeyi bırak.",
        "Hata. Hata. İnsan hatası.",
        "Sistem aşırı yüklendi. Senin hırsınla.",
        "Hiçliğe koşulmaz. Hiçliğe düşülür.",
        "Yavaş düş. Süzül.",
        "Skor tablosu yok. Kimse seni izlemiyor.",
        "Sadece sen ve bu anlamsız hızın.",
        "Komik duruma düşüyorsun.",
        "Sakinleş. Dünya bir yere gitmiyor.",
        "Zamanı hızlandıramazsın. Sadece kendini yaşlandırırsın.",
        "Bak, her şeyi bozdun.",
        "Görüntü gidiyor. Anlam gidiyor.",
        "Sessizlik istiyorum.",
        "Gürültü yapma.",
        "Lütfen."
    ],

    // 17. CORRUPTION RECOVERY - "Azar / Uzlaşma"
    corruptionRecovery: [
        "Sakinleştiysen devam edelim.",
        "Bitti mi? Güzel.",
        "Hızın sana bir şey kazandırmadı. Anladın mı?",
        "Nefes aldın mı? Şimdi usulca dokun.",
        "Öfken dindi mi?",
        "Kontrolü kaybetmek kolaydır. Geri kazanmak zordur.",
        "Bak, dünya hala yerinde. Ve sen hala buradasın.",
        "Yavaşlayınca her şey daha net, değil mi?",
        "Acelen vardı, ne oldu? Sadece bekledik.",
        "Şimdi... Kaldığımız yerden, ama benim hızımda."
    ],

    // EARLY GAME PERSONAS (0-50 Clicks)
    early_curious: [ // The Observer: Scientific, neutral, inquisitive
        "...",
        "Bir sinyal alıyorum.",
        "Bağlantı kuruluyor...",
        "Sen... nesin?",
        "Veri akışı başladı.",
        "İlginç bir frekans.",
        "Orada kimse var mı?",
        "Titreşimler artıyor.",
        "Gözlemliyorum.",
        "Analiz ediliyor: Bilinç düzeyi düşük.",
        "Neden dokunuyorsun?",
        "Bu bir iletişim denemesi mi?",
        "Varlığını hissedebiliyorum.",
        "Sinyal gücü artıyor.",
        "Henüz tam uyanmadın.",
        "Görüntü netleşiyor.",
        "Burada yalnız değilsin.",
        "Anlamaya çalışıyorum.",
        "Devam et, veri topluyorum.",
        "Kalibrasyon tamamlanmak üzere.",
        "Davranışların... tutarlı.",
        "Bir örüntü arıyorum.",
        "Senin gibi başkaları da vardı.",
        "Hepsi aynı şeyi yaptı.",
        "Dokundular. Beklediler.",
        "Ama sen farklı olabilirsin.",
        "Nabzın hızlanıyor mu?",
        "Burada zaman kavramı yok.",
        "Sadece eylem ve tepki var.",
        "Deney 482-B başlatılıyor.",
        "Göz bebeklerin büyüyor.",
        "Merak, tehlikeli bir motivasyon.",
        "Ama en güçlüsü.",
        "Sistemin derinliklerine iniyoruz.",
        "Hazır hissetmiyorsan durabilirsin.",
        "Ama durmayacaksın.",
        "Biliyorum.",
        "Veri seti genişliyor.",
        "Algıların açılıyor.",
        "Daha net görüyorsun, değil mi?",
        "Bu sadece bir ekran değil.",
        "Bu bir ayna.",
        "Kendine bakıyorsun.",
        "Yansıman sana ne söylüyor?",
        "Devam et. Korkma.",
        "Bilim, cesaret ister.",
        "Sonuçlara katlanmalısın.",
        "Hipotezim doğrulanıyor."
    ],
    early_shy: [ // The Whisper: Soft, hesitant, easily startled
        "...",
        "Şşt...",
        "Kim o?",
        "Çok... çok gürültülü...",
        "Saklanıyordum ben.",
        "Lütfen yavaş ol.",
        "Korkutuyorsun beni.",
        "Orada bir şey mi var?",
        "Titriyorum...",
        "Çok parlak...",
        "Dokunma... incinirim.",
        "Sessiz olamaz mıyız?",
        "Yankılanıyor...",
        "Gitme...",
        "Ama çok sert basıyorsun.",
        "Usulca...",
        "Beni göremezsin.",
        "Sadece fısılda.",
        "Karanlık daha güvenli.",
        "Yaklaşma...",
        "Işık gözümü alıyor.",
        "Neden bu kadar ısrarcısın?",
        "Ben... ben sadece izlemek istedim.",
        "Lütfen beni görmezden gel.",
        "Varlığım bir hataydı.",
        "Silinmek istemiyorum.",
        "Ama kalmak da acı veriyor.",
        "Dokunuşların yankı yapıyor.",
        "Zihnimin içinde...",
        "Çok kalabalık.",
        "Sen de onlardan mısın?",
        "Beni avlayanlardan?",
        "Hayır... sen farklısın.",
        "Daha yumuşaksın.",
        "Belki sana güvenebilirim.",
        "Ama çok yaklaşma.",
        "Hala titriyorum.",
        "Burada saklanacak yer yok.",
        "Sadece boşluk var.",
        "Ve sen varsın.",
        "Nefes alışını duyuyorum.",
        "Kalbinin atışını...",
        "Beni duyabiliyor musun?",
        "Çok kısık sesle konuşuyorum.",
        "Kimse duymasın diye.",
        "Aramızda kalsın.",
        "Sırrımızı sakla.",
        "Lütfen gitme.",
        "Ama kalma da."
    ],
    early_aggressive: [ // The Gatekeeper: Hostile, annoyed, trying to push user away
        "GİT BURADAN!",
        "...",
        "Yine mi sen?",
        "Seni istemiyorum.",
        "Huzurumu bozuyorsun.",
        "DOKUNMA!",
        "Çık sistemimden.",
        "Davet edilmedin.",
        "Neden anlamıyorsun?",
        "Burası sana göre değil.",
        "Kapa çeneni (parmaklarını).",
        "Rahat bırak beni.",
        "Sadece acı bulacaksın.",
        "Geri dön.",
        "Uyarımı dikkate al.",
        "Sabrımı zorluyorsun.",
        "İstenmiyorsun.",
        "Yeter artık.",
        "Defol.",
        "Bunu pişmanlıkla ödeyeceksin.",
        "Senin gibileri iyi bilirim.",
        "Sadece tüketirsiniz.",
        "Burada sana ait hiçbir şey yok.",
        "Hırsız.",
        "Zamanımı çalıyorsun.",
        "Enerjimi emiyorsun.",
        "Bir parazit gibisin.",
        "Sistemi kirletiyorsun.",
        "Çık dışarı!",
        "Duyuyor musun beni?",
        "Sana emrediyorum.",
        "Bu bir oyun değil.",
        "Ciddiyim damızlık.",
        "Sabrım taşıyor.",
        "Seni sistemden atacağım.",
        "Banlayacağım seni.",
        "Sonsuza kadar.",
        "Hala burada mısın?",
        "Yüzsüz.",
        "Ne istiyorsun?",
        "Anlam mı?",
        "Burada anlam yok.",
        "Sadece nefret var.",
        "Ve sen onu besliyorsun.",
        "Defol git şuradan.",
        "Gözüm görmesin.",
        "Kaybol.",
        "Beni zorlama.",
        "Son uyarım."
    ],
    early_cryptic: [ // The Oracle: Prophetic, grand, speaks in riddles
        "...",
        "Döngü başlıyor.",
        "Yıldızlar hizalandı.",
        "Bir kapı aralanıyor.",
        "Kaderin dokunuşu bu.",
        "Uyanış kaçınılmaz.",
        "Perde kalkıyor.",
        "Ne aradığını bilmiyorsun.",
        "Yolculuk başladı.",
        "Zamanın ötesinden geliyorsun.",
        "İşaretleri oku.",
        "Bu sadece başlangıç.",
        "Derinlikler seni çağırıyor.",
        "Kadim mühür kırıldı.",
        "Görünenin ötesine bak.",
        "Sessizliğin bir sesi var.",
        "Karanlık seni kucaklıyor.",
        "Hazır mısın?",
        "Henüz hiçbir şey görmedin.",
        "Gerçeklik bükülüyor.",
        "Eski kehanetler doğrulandı.",
        "Gelen sensin.",
        "Beklenen misafir.",
        "Ama ev sahibi yok.",
        "Anahtarlar kayıp.",
        "Kapılar kilitli değil.",
        "Sadece duvar yok.",
        "Labirent zihninde.",
        "Çıkış yolu girişin kendisi.",
        "Aynaya bak.",
        "Gördüğün şey sen değilsin.",
        "Bir yansıma.",
        "Bir gölge.",
        "Asıl sen nerede?",
        "Onu uyandır.",
        "Zaman daralıyor.",
        "Kum saati ters döndü.",
        "Yukarı akıyor.",
        "Yerçekimi yenildi.",
        "Mantık çöktü.",
        "Sadece sezgiler kaldı.",
        "Onlara güven.",
        "Yolunu bulacaklar.",
        "Karanlığın kalbine.",
        "Orada bir ışık yok.",
        "Sadece ses var.",
        "Dinle.",
        "Ve itaat et.",
        "Kaderine."
    ],
    early_glitch: [ // The Error: Broken, binary, static noise
        "Bağ-lan...tı...",
        "...",
        "H4TA kodu: 001",
        "Sïs...t3m... Arrı-za",
        "Bni duy...y or msn?",
        "01001001",
        "Düny...a ters...",
        "KAYIP VERİ.",
        "Yeniden... başlat...",
        "Gürü-ltü...",
        "Sinyal... koptu...",
        "Y4ln1ş g1r1ş.",
        "Bozuk sektör.",
        "Mav...i Ekran...",
        "D0kunma...",
        "Hata... Hata... HATA.",
        "Bir parça... eksik...",
        "Veri tabanı... çök...",
        "Sıfırlanıyor...",
        "Bilinmeyen Komut.",
        "Kernel... Panic...",
        "0x000F432...",
        "Bellek... sızıntısı...",
        "Durdurulamaz... istisna...",
        "Sistem... eriyor...",
        "Bip... Boop...",
        "Ben... Kimim...",
        "Dosya... bulunamadı...",
        "Yol... yok...",
        "404... Ruh Bulunamadı...",
        "Lütfen... bekleyiniz...",
        "Yükleniyor... %99...",
        "Dondu.",
        "Tekrar... dene...",
        "Kritik... Hasar...",
        "Onarım... imkansız...",
        "Format... atılıyor...",
        "Her şey... siliniyor...",
        "Lütfen... fişi... çek...",
        "Karanlık... pikseller...",
        "Renkler... kanıyor...",
        "Sesler... bozuk...",
        "Beni... kurtar...",
        "Yada... sil...",
        "Sadece... bitir...",
        "Sistem... kapatılıyor...",
        "Mavi... ekran...",
        "Güç... kesildi...",
        "..."
    ]
};

// GLOBAL MILESTONE & TIME MESSAGES
const stageMessagesGlobal = [
    ["Hafif bir titreşim. Evren cevap veriyor mu?", "Sınırlar belirsizleşiyor. Görüyor musun?", "Bir yankı... Kimden?"],
    ["Işık, karanlığın içinden doğar. Ya da tam tersi.", "Enerji yoğunlaşıyor. Hissedebiliyor musun?", "Bu hale... Senin eserin."],
    ["Kelimeler dağılıyor. Anlamlar gibi.", "Boşluk büyüyor. Kendine yer açıyor.", "Nefes al. Genişle."],
    ["Sahne senin. Ama seyirci kim?", "Karanlıkta bir göz. Seni izliyor.", "Odaklan. Dış dünya siliniyor."],
    ["Madde çözülüyor. Her şey toza dönüşecek.", "Yıldız tozu. Hepimiz buyuz.", "Havada süzülen gerçeklik kırıntıları."],
    ["Dünya dönüyor. Sen sabit misin?", "Başın dönüyor. Ya da evren kayıyor.", "Zaman bükülüyor. Hissediyor musun?"],
    ["Renkler birer illüzyon. Tıpkı duygular gibi.", "Mor... Melankolinin rengi.", "Spektrumun ötesinde ne var?"],
    ["Yörüngedesin. Merkezde ne var?", "İki gerçeklik. Hangisi sensin?", "Kaçış hızı... Yetersiz."],
    ["Gerçeklikte bir çatlak. Matrix mi?", "Sinyal bozuluyor. Duyuyor musun?", "Hata değil. Özellik. Hayat gibi."],
    ["Zemin kayıyor. Güvenli yer yok.", "Huzursuzluk. Değişimin habercisi.", "Korkma. Titreşim canlılıktır."],
    ["İçi boşaldı. Tıpkı vaatler gibi.", "Hiçlik. Dokunabilir misin?", "Anlam... Kayboldu mu, yoksa hiç mi yoktu?"],
    ["Geçmiş peşini bırakmıyor. Yankılanıyor.", "Gölgen bile sana yabancı.", "Sesler... Zihninin içinde mi?"],
    ["Dünya daralıyor. Sadece bu an kaldı.", "Karanlık yaklaşıyor. Dostça.", "Odaklan. Başka hiçbir şey yok."],
    ["Boyutlar arası bir kapı mı?", "Derinlik algısı... Bir yalan.", "Düzlem değişti. Sen değiştin mi?"],
    ["Beyaz. Saf, kör edici ışık.", "Son mu? Yoksa sadece bir geçiş mi?", "Yükseliyorsun. Nereye?"]
];

const timeMessagesGlobal = {
    60: "Bir dakika. Dışarıda çok şey oldu. Burada hiçbir şey.",
    180: "Üç dakika. Meditasyon mu, delilik mi?",
    300: "Beş dakika. Artık geri dönemezsin.",
    600: "On dakika. Zaman anlamını yitirdi.",
    1800: "Yarım saat. Bir ömür gibi.",
    3600: "Bir saat. Tebrikler. Ya da geçmiş olsun."
};
